password = input('Put a password')
print(f'Does the text contains only spaces? {password.isspace()}')
print(f'Does the text contains only numbers? {password.isnumeric()}')
print(f'Does the text contains only letters? {password.isalpha()}')
print(f'Is it alphanumeric? letters and numbers {password.isalnum()}')
print(f'Is it in ALL CAPS? {password.isupper()}')
print(f'Is it in lowercase? {password.islower()}')
print(f'Is it capitalized with the first letter? {password.istitle()}')
print(f'Is this just standard characters? {password.isascii()}')
